# FROM nvcr.io/nvidia/tensorflow:19.08-py3
## MAINTAINER Paweł Sołtysiak <psoltysiak@nvidia.com>

FROM docker.io/ibmcom/powerai:1.6.1-all-ubuntu18.04-py3-ppc64le

ADD . /workspace/rn50v15_tf
WORKDIR /workspace/rn50v15_tf
# RUN pip install -r requirements.txt
